# Use Node.js image
FROM node:18

# Set working directory
WORKDIR /app
# Copy files
COPY . .

# Install dependencies
RUN npm install

# Expose the default Vite dev server port
EXPOSE 5173

# Start Vite dev server
CMD ["npm", "run", "dev", "--", "--host"]
